### PR TITLE
References to unaligned fields are an error

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes https://github.com/ferrocene/specification/issues/144

### CODE REVIEW

**Review by kirtchev-adacore — APPROVED** [review]

**Comment by kirtchev-adacore** [comment]
bors merge

**Comment by Veykril** [comment]
@kirtchev-adacore I believe we said we would allow future compat lints?

**Comment by kirtchev-adacore** [comment]
@Veykril The consensus is that we will describe the behavior of the baseline (1.66 or 1.67), whatever that behavior might be. If something is flagged with a warning at the time of cutting the baseline and it is not yet an error, then it is technically legal.

**Comment by Veykril** [comment]
Ah I didn't realize this lint changed to error by default by now

**Pull request merged**
