### PR TITLE
Clarify that `UnicodeEscape` doesn't include surrogates and noncharacters

### LINKED ISSUE #407: Section 2.4.4: UnicodeEscape definition does not exclude Unicode surrogate code points and noncharacters
In [Section 2.4.4 Character Literals](https://spec.ferrocene.dev/lexical-elements.html#character-literals), the definition [`UnicodeEscape`](https://spec.ferrocene.dev/lexical-elements.html#syntax_unicodeescape) does not explicitly exclude Unicode surrogate code points. In the official Rust compiler, this throws an error as shown below.

I believe this can be fixed by also including a note after the syntax block definition, like in 2.4.4:1 for the [`CharacterLiteralCharacter`](https://spec.ferrocene.dev/lexical-elements.html#syntax_characterliteralcharacter) definition. I'd be happy to send a pull request! :)

## Code example
([Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=15fcf00366aeee316977313d53f2a5fa))
```rs
fn main() {
    println!("{}", matches!('c', '\u{D800}'..='\u{DBFF}'));
}
```
```
error: invalid unicode character escape
 --> src/main.rs:2:35
  |
2 |     println!("{}", matches!('c', '\u{D800}'..='\u{DBFF}'));
  |                                   ^^^^^^^^ invalid escape
  |
  = help: unicode escape must not be a surrogate

error: invalid unicode character escape
 --> src/main.rs:2:48
  |
2 |     println!("{}", matches!('c', '\u{D800}'..='\u{DBFF}'));
  |                                                ^^^^^^^^ invalid escape
  |
  = help: unicode escape must not be a surrogate
```

### PR DESCRIPTION
**Pull request by neoncitylights**
Fixes #407

### CODE REVIEW

**Review by kirtchev-adacore — DISMISSED** [review]
bors merge

**Comment by kirtchev-adacore** [comment]
@neoncitylights Thank you for finding and fixing this issue!

**Comment by kirtchev-adacore** [comment]
@pietroalbini The CI uncovered a warning:
```
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
```

**Comment by neoncitylights** [comment]
> That warning is "expected" but harmless, it just means a new release of `pip` is available (but we don't need it). The actual watrainingrning/error is the lack of the paragraph ID on the new one:
> 
> ```
> /home/runner/work/specification/specification/src/lexical-elements.rst:1013: WARNING: paragraph should have an id
> ```
> 
> @neoncitylights you can generate random IDs with the `generate-random-ids.py` script at the top of the repo, and put one of those IDs at the start of the paragraph (like it's done with the other paragraphs).

Hi, thank you for pointing me in the right direction, and apologies for the wait! I tried running the Python script as suggested, and was able to build the HTML document locally, but unfortunately CI is saying that "ffi.html:959: id is not unique: `syntax_unicodeescape`". Is there a way I can fix this? Thank you again!

image

**Comment by neoncitylights** [comment]
That makes sense! I'll work on adjusting the description of `UnicodeEscape` so it's definition and syntax is still clear in the description :)

**Review by kirtchev-adacore — APPROVED** [review]
bors merge

**Pull request merged**
